--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/mcbeany-pm-pl/BetterMinion
build-by-default: true
branches:
  - master
projects:
  BetterMinion:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
        branch: PM-4.0
      - src: Muqsit/InvMenu/InvMenu
        version: ^4.3.4
        branch: "4.0"
...
