---
name: BetterMinion
version: 0.0.1
main: Mcbeany\BetterMinion\BetterMinion
api: 4.0.0
src-namespace-prefix: Mcbeany\BetterMinion
description: A plugin that adds minions to your Minecraft Server
...